### ISSUE TITLE
Update remote plugins throwing error

### ISSUE THREAD

**Issue by aareman** [ms-jpq/chadtree#1]
Looks like a cool plugin. Would love to try (the session support is what caught my eye)

here is the output of `:UpdateRemotePlugins` getting an import error
```
Encountered ImportError loading plugin at /home/avraham/.config/nvim/plugged/chadtree
/rplugin/python3/chadtree: cannot import name 'create_task'
Traceback (most recent call last):
  File "/home/avraham/.local/lib/python3.6/site-packages/pynvim/plugin/host.py", line
 171, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
ImportError: cannot import name 'create_task'
remote/host: python3 host registered plugins []
```

checkhealth
![image](https://user-images.githubusercontent.com/10500823/89077806-0fda5500-d351-11ea-9d7b-f731d7468f98.png)
![image](https://user-images.githubusercontent.com/10500823/89077831-18cb2680-d351-11ea-9481-962c3bd178a3.png)

```
:version
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LE
VEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=g
nu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiag
nostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_
FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/bui
ld/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/ne
ovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim
/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neo
vim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"
```

**Comment by ms-jpq** [comment]
@aareman 

Im sorry, I cannot support `python3.6`, it is very close to EOL at this point.  More importantly `3.7` introduced too many useful features like `dataclass`, and such, that you would require [third party](https://pypi.org/project/dataclasses/) libraries implementations for.

If I had more time and resources I would look into supporting older `python` versions, but at this time I do not.

**Comment by aareman** [comment]
If a python update is all that's needed. I can do that :smile: thanks for the fast feedback. I'll let you know if i still have an issue
