### ISSUE TITLE
Some keybindings are not working

### ISSUE THREAD

**Issue by anasem** [ms-jpq/chadtree#10]
Thanks for the nice work!

I couldn't get some of the keybindings to work. In particular [.] for toggling hidden files view and Ctrl+r.

Also could you add a shortcut for opening in a new tab?

**Comment by ms-jpq** [comment]
Hi there,

I think the bindings not working thing could be because I never explained how they work, `<c-r>` just does a refresh, but did not print out a message before, so if nothing changed, you won't see any updates.

I updated it so that it now prints out a message before and after it refreshes.

Are you using the `.` key in a git repo? By default it only hides `.DS_Store` cache and `.git` folder, and also stuff thats hidden by `.gitignore` if you are inside a git repo. Otherwise, it does not hide dotfiles by default, you will have to add a `.*` thing to `g:chadtree_ignores`.

i.e.
```vimL
lua vim.api.nvim_set_var("chadtree_ignores", { name = {".*", ".git"} })
```

I also added a short cut for opening in new tabs, you will have to do `:UpdateRemotePlugins` and restart, then you can use `<m-enter>`.

I hope this solves your problems

**Comment by anasem** [comment]
Thanks a lot! it works perfectly now. 

One more thing I noticed when I set  a filter I get an error message if there is no valid glob filter 

```python
Traceback (most recent call last):
  File "/home/anas/.vim/bundle/chadtree/rplugin/python3/chadtree/__init__.py", line 75, in run                                                                                                              
    fut.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/anas/.vim/bundle/chadtree/rplugin/python3/chadtree/__init__.py", line 93, in run
    new_state = await fn(
  File "/home/anas/.vim/bundle/chadtree/rplugin/python3/chadtree/transitions.py", line 389, in c_filter
    new_state = await forward(
  File "/home/anas/.vim/bundle/chadtree/rplugin/python3/chadtree/state.py", line 120, in forward
    lookup, rendered = render(
  File "/home/anas/.vim/bundle/chadtree/rplugin/python3/chadtree/render.py", line 206, in render
    lookup, rendered = zip(*render(node, depth=0, cleared=False))
ValueError: not enough values to unpack (expected 2, got 0)
not enough values to unpack (expected 2, got 0)
```

**Comment by ms-jpq** [comment]
Thanks for the catch, I fixed it

https://github.com/ms-jpq/chadtree/commit/799b789d36aedf5be8e67668bad7ecb65af022aa
