### ISSUE TITLE
Invalid window ID when performing most actions

### ISSUE THREAD

**Issue by ceuk** [ms-jpq/chadtree#105]
Occurs when opening chadtree, moving around, opening directories, performing various other actions.

Neovim:  v0.5.0-dev+950-g5ce328df4 (nightly)

Python: 3.9.1

Pynvim: 0.4.1

Error + stack trace:

```
Error detected while processing function CHADon_stderr:
line    1:
Invalid window id: 1058
Traceback (most recent call last):
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/client.py", line 92, in wait
    threadsafe_call(nvim, cont)
  File "/home/ceuk/.config/nvim/plugged/chadtree/.vars/runtime/pynvim_pp/lib.py", line 41, in threadsafe_call
    return cast(T, fut.result())
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/ceuk/.config/nvim/plugged/chadtree/.vars/runtime/pynvim_pp/lib.py", line 32, in cont
    ret = fn(*args, **kwargs)
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/client.py", line 82, in cont
    stage = cast(AnyFun[Optional[Stage]], handler)(
  File "/home/ceuk/.config/nvim/plugged/chadtree/.vars/runtime/pynvim_pp/rpc.py", line 50, in __call__
    return cast(T, self._handler(nvim, *args, **kwargs))
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/transitions/click.py", line 64, in _primary
    return _click(
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/transitions/click.py", line 45, in _click
    nxt = open_file(
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/transitions/shared/open_file.py", line 111, in open_file
    _show_file(nvim, state=new_state, settings=settings, click_type=click_type)
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/transitions/shared/open_file.py", line 86, in _show_file
    resize_fm_windows(nvim, state.width)
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/transitions/shared/wm.py", line 145, in resize_fm_windows
    for window in find_fm_windows_in_tab(nvim):
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/transitions/shared/wm.py", line 65, in find_fm_windows_in_tab
    for win in find_windows_in_tab(nvim, no_secondary=True):
  File "/home/ceuk/.config/nvim/plugged/chadtree/chadtree/transitions/shared/wm.py", line 50, in find_windows_in_tab
    if not no_secondary or not win_get_option(nvim, win=win, key="previewwindow"):
  File "/home/ceuk/.config/nvim/plugged/chadtree/.vars/runtime/pynvim_pp/api.py", line 63, in win_get_option
    opt: T = nvim.api.win_get_option(win, key)
  File "/home/ceuk/.local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/ceuk/.local/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Invalid window id: 1058
```

**Comment by GaetanLepage** [comment]
Same problem here :/

**Comment by ms-jpq** [comment]
edit:

I actually have no idea why this happens for most actions. There must be some window in the background that gets opened and closed between CHADTree's calls to neovim, which would be unexpected, but there are also a million vim plugins, and some of them could either be bugged, or some how have a valid use case for these ephemeral windows. 

Unfortunately there is no way for me to do blocking calls without blocking the event loop itself, so this one might be hard to solve.

**Comment by ceuk** [comment]
bummer - do you know if there's a way I can debug/step through what's happening on my system? Might be able to identify the plugin that's the culprit and remove or raise an issue there

**Comment by ms-jpq** [comment]
it would be helpful if i could get like a list of ur plugins, i can try to debug it.

 :) thank you!

**Comment by ms-jpq** [comment]
also what timezone are you all at lol, its 3 am and i got like 5 messages in the past hour

**Comment by ceuk** [comment]
haha it's midday here (GMT) :)

here's my plugins:

nvim-treesitter/nvim-treesitter
romainl/vim-qf
tpope/vim-unimpaired
gillyb/stable-windows
datwaft/bubbly.nvim
skamsie/vim-lineletters
dstein64/nvim-scrollview
yggdroot/indentline
neomutt/neomutt.vim
rhysd/committia.vim
gioele/vim-autoswap
camspiers/animate.vim
wellle/visual-split.vim
tpope/vim-dadbod
kristijanhusak/vim-dadbod-ui
hotwatermorning/auto-git-diff
scrooloose/nerdtree
ms-jpq/chadtree
tiagofumo/vim-nerdtree-syntax-highlight
ryanoasis/vim-devicons
kyazdani42/nvim-web-devicons
AndrewRadev/tagalong.vim
tomtom/tcomment_vim
metakirby5/codi.vim
szw/vim-maximizer
airblade/vim-gitgutter
fatih/vim-go
sheerun/vim-polyglot
neoclide/coc.nvim
kkoomen/vim-doge
heavenshell/vim-jsdoc
majutsushi/tagbar
tpope/vim-fugitive
mhinz/vim-startify
wellle/targets.vim
segeljakt/vim-silicon
psliwka/vim-smoothie
hail2u/vim-css3-syntax
tpope/vim-haml
mattn/emmet-vim
kshenoy/vim-signature
christoomey/vim-conflicted
iamcco/markdown-preview.nvim
rrethy/vim-hexokinase
peitalin/vim-jsx-typescript
HerringtonDarkholme/yats.vim
leafgarland/typescript-vim
puremourning/vimspector
liuchengxu/vim-which-key
unblevable/quick-scope
ludovicchabant/vim-gutentags
tmhedberg/matchit
APZelos/blamer.nvim


there are.. a few

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/171

might fix, i gotta test it out for a while and if it works ill merge it

**Comment by ms-jpq** [comment]
i think its fixed? ill close it, please reopen if you still have issues :D
