### ISSUE TITLE
Ungraceful handle of `Ctrl-c` during file [re]naming

### ISSUE THREAD

**Issue by ajpeacock0** [ms-jpq/chadtree#108]
**Action**: When accepting input for `new` or `rename`, `Ctrl-c` is hit to cancel the command

**Expected**: Text input to disappear and command cancelled 
**Occurred**: The following error is shown to the user: 
```
pynvim.api.common.NvimError: Keyboard interrupt
--  CHADTree
level:    ERROR
time:     2021-01-21 10:25:37
module:   __init__
line:     101
function: run
message:  |-
Keyboard interrupt
Traceback (most recent call last):
  File "C:/Users/<user>/AppData/Local/nvim/plugged/chadtree/rplugin/python3\chadtree\__init__.py", line 99, in run
    fut.result()
  File "C:\Users\<user>\scoop\apps\python\current\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\<user>\scoop\apps\python\current\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:/Users/<user>/AppData/Local/nvim/plugged/chadtree/rplugin/python3\chadtree\__init__.py", line 118, in run
    stage = await fn(
  File "C:/Users/<user>/AppData/Local/nvim/plugged/chadtree/rplugin/python3\chadtree\transitions.py", line 561, in c_rename
    child = await call(nvim, ask)
  File "C:/Users/<user>/AppData/Local/nvim/plugged/chadtree/rplugin/python3\chadtree\nvim.py", line 28, in cont
    ret = fn()
  File "C:/Users/<user>/AppData/Local/nvim/plugged/chadtree/rplugin/python3\chadtree\transitions.py", line 558, in ask
    resp = nvim.funcs.input(LANG("pencil"), rel_path)
  File "C:\Users\<user>\AppData\Roaming\Python\Python38\site-packages\pynvim\api\nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "C:\Users\<user>\AppData\Roaming\Python\Python38\site-packages\pynvim\api\nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "C:\Users\<user>\AppData\Roaming\Python\Python38\site-packages\pynvim\msgpack_rpc\session.py", line 104, in request
    raise self.error_wrapper(err)
```

_This error should be gracefully handled and the command should silently cancel._

## Found on

```
$ nvim --version
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

System: Windows 10

**Comment by ms-jpq** [comment]
wait wtf thats amazing, you can send `Keyboard interrupt`!

Also I think you are on the old branch, please update to the newer version and run `:UpdateRemotePlugins` as well as `:CHADdeps`  after.

I will fix this thingy after I get some sleep, but wow im amazed the client would send `Keyboard interrupt` events.

edit:

MIght come in handy 

https://github.com/ms-jpq/chadtree/blob/chad/docs/MIGRATION.md

**Comment by ajpeacock0** [comment]
Thanks for the super quick response! Yea I'm on the `legacy` branch due to being on Windows and so I'm including CHADtree like so, since `chad` branch breaks for me:
```
Plug 'ms-jpq/chadtree', {'branch': 'legacy', 'do': ':UpdateRemotePlugins'}
```

I'm not sure how this issue might repro on your latest version, but I'll check as soon as I can run `chad` successfully 😋

**Comment by ms-jpq** [comment]
ok yeah sorry about not getting windows to work first.

I will update you when I do. I just had to push it out because I was afraid to get burn out if I didn't deliver something after working so many hours on this.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/123

will close `c-c`. next PR will close window support

will close

https://github.com/ms-jpq/chadtree/pull/124

**Comment by ms-jpq** [comment]
windows now works

**Comment by ajpeacock0** [comment]
Awesome - I confirm the fix in `chad` branch works on Windows! Thanks for continuing to improve the best File Manager 😀
