### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by qianqiangliu** [ms-jpq/chadtree#129]
Error detected while processing function CHADon_stderr:
line    1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 144, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jacky/.config/nvim/plugged/chadtree/chadtree/__main__.py", line 42
    command: Union[Literal["deps"], Literal["run"]] = args.command
           ^
SyntaxError: invalid syntax

**Comment by ms-jpq** [comment]
oh sorry the minimal python version is `3.8.2`

because I had to write my own [pdantic](https://pydantic-docs.helpmanual.io/)

python 3.5 is end of life anyways :d, maybe you can upgrade.

sorry there is no way for me to go down versions at this point, its way too late
