### ISSUE TITLE
Error detected while processing function CHADon_stderr

### ISSUE THREAD

**Issue by marcoaaguiar** [ms-jpq/chadtree#162]
I keep getting the error below when I issue some commands that are not related to CHADTree, for instance, this one happened after I dit a "go to definition" on `coc`.
This happens when the CHADTree window is closed. If I find any other pattern I will post it here.

```bash
Error detected while processing function CHADon_stderr:
line    1:
Invalid window id: 1008
Traceback (most recent call last):
  File "/home/marco/.config/nvim/plugged/chadtree/chadtree/client.py", line 115, in wait
    threadsafe_call(nvim, cont)
  File "/home/marco/.config/nvim/plugged/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 41, in threadsafe_call
    return cast(T, fut.result())
  File "/home/marco/.pyenv/versions/3.9.1/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/home/marco/.pyenv/versions/3.9.1/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/marco/.config/nvim/plugged/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 32, in cont
    ret = fn(*args, **kwargs)
  File "/home/marco/.config/nvim/plugged/chadtree/chadtree/client.py", line 98, in cont
    redraw(nvim, state=self._state, focus=stage.focus)
  File "/home/marco/.config/nvim/plugged/chadtree/chadtree/transitions/redraw.py", line 54, in redraw
    for win, buf in find_fm_windows(nvim):
  File "/home/marco/.config/nvim/plugged/chadtree/chadtree/transitions/shared/wm.py", line 61, in find_fm_windows
    buf = win_get_buf(nvim, win=win)
  File "/home/marco/.config/nvim/plugged/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/api.py", line 54, in win_get_buf
    buf: Buffer = nvim.api.win_get_buf(win)
  File "/home/marco/.config/nvim/plugged/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/marco/.config/nvim/plugged/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Invalid window id: 1008
Press ENTER or type command to continue
```

**Comment by cseickel** [comment]
I get this as well, I'm pretty sure it is caused by my scrollbar plugin:

https://github.com/dstein64/nvim-scrollview

Disabling that makes the problem go away.

**Comment by marcoaaguiar** [comment]
@cseickel  I'm not using this plugin, but I'm using https://github.com/psliwka/vim-smoothie, which might be doing similar buffer scans.

**Comment by Mte90** [comment]
![Screenshot_20220610_122346](https://user-images.githubusercontent.com/403283/173046208-875ccfa5-7e2a-445c-b212-93208be5ba1d.png)

Same issue but I see from the code that is generate by different stuff.
