### ISSUE TITLE
Failed to start with `list_bufs() got an unexpected keyword argument 'listed'`

### ISSUE THREAD

**Issue by beeender** [ms-jpq/chadtree#183]
I am using [packer](https://github.com/wbthomason/packer.nvim) with chadtree.
It was working fine before the update this morning.

nvim: `v0.5.0-dev+1325-gdab6b08a1`
Python: `3.9.5`
chadtree: `a74d2cff21b3d0f1152e615c0b4223ef890fdd76`

I have executed `CHADdeps` after the updating.

Then the `CHADopen` gives me below error:

```
Error detected while processing function CHADon_stderr:
line    1:
list_bufs() got an unexpected keyword argument 'listed'
Traceback (most recent call last):
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/client.py", line 127, in wait
    threadsafe_call(nvim, cdraw)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 41, in threadsafe_call
    return cast(T, fut.result())
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 32, in cont
    ret = fn(*args, **kwargs)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/client.py", line 108, in cdraw
    stage = handler(nvim, self._state, settings, *args)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/rpc.py", line 50, in __call__
    return cast(T, self._handler(nvim, *args, **kwargs))
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/transitions/toggle_open.py", line 170, in _open
    _open_fm_window(nvim, settings=settings, opts=opts, width=new_state.width)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/transitions/toggle_open.py", line 96, in _open_fm_window
    buf = next(find_fm_buffers(nvim), None)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/transitions/shared/wm.py", line 89, in find_fm_buffers
    for buf in list_bufs(nvim, listed=True):
TypeError: list_bufs() got an unexpected keyword argument 'listed'
```

**Comment by ms-jpq** [comment]
Please run `:CHADdeps`,

**Comment by beeender** [comment]
![image](https://user-images.githubusercontent.com/449296/118447481-66b7ec00-b723-11eb-804f-131028e92b2c.png)

I did, is there anything I missed?

**Comment by ms-jpq** [comment]
sorry that is weird, can you please update and run again if you don't mind?

**Comment by beeender** [comment]
sure, is there anything I can delete to make sure a clean `CHADdeps`?

**Comment by ms-jpq** [comment]
nono please just run it, if it doesn't work then I have a bug some where, I apologize for the inconvenience.

I think the issue is that I accidentally pushed out a bad commit, but if it doesn't work then I have screwed something up.

Just so you can get it working in the main time, if `CHADdeps` after update doesn't work, `rm -rf <chadtree>/.vars` will clean it all up

**Comment by beeender** [comment]
The chadtree is at a74d2cff21b3d0f1152e615c0b4223ef890fdd76

Then I ran `CHADdeps`
got:
```
Error detected while processing function CHADon_stderr:
line    1:
---
This is not an error:
You can now use :CHADopen
Press ENTER or type command to continue
```

Then `CHADopen` before/after restarting nvim gives me the same error
```Error detected while processing function CHADon_stderr:
line    1:
list_bufs() got an unexpected keyword argument 'listed'
Traceback (most recent call last):
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/client.py", line 127, in wait
    threadsafe_call(nvim, cdraw)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 41, in threadsafe_call
    return cast(T, fut.result())
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line 32, in cont
    ret = fn(*args, **kwargs)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/client.py", line 108, in cdraw
    stage = handler(nvim, self._state, settings, *args)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/rpc.py", line 50, in __call__
    return cast(T, self._handler(nvim, *args, **kwargs))
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/transitions/toggle_open.py", line 170, in _open
    _open_fm_window(nvim, settings=settings, opts=opts, width=new_state.width)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/transitions/toggle_open.py", line 96, in _open_fm_window
    buf = next(find_fm_buffers(nvim), None)
  File "/home/cc/.local/share/nvim/site/pack/packer/start/chadtree/chadtree/transitions/shared/wm.py", line 89, in find_fm_buffers
    for buf in list_bufs(nvim, listed=True):
TypeError: list_bufs() got an unexpected keyword argument 'listed'

```

**Comment by ms-jpq** [comment]
thank you so much for the report, please use the workaround by doing a `rm -rf on <chadtree install folder>/.vars` or just `<chadtree install folder>` itself and reinstall.

it should get you running in the main time, I am not sure why its not working, but I will look at it now,

thank you for your patience

**Comment by beeender** [comment]
[debug_vars.zip](https://github.com/ms-jpq/chadtree/files/6492076/debug_vars.zip)

deleting `.var` helps!
I uploaded the good and bad `.vars`. Maybe it helps for debugging.

**Comment by ms-jpq** [comment]
thank u!

i think i fixed it now

https://github.com/ms-jpq/chadtree/pull/185
