### ISSUE TITLE
Error when calling CHADopen

### ISSUE THREAD

**Issue by mhartington** [ms-jpq/chadtree#2]
Getting this python error when calling the open command

```
Traceback (most recent call last):
  File "/Users/mhartington/.config/nvim/.cache/init.vim/.dein/rplugin/python3/chadtree/__init__.py", line 72, in run
    fut.result()
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 435, in resul
t
    return self.__get_result()
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get
_result
    raise self._exception
  File "/Users/mhartington/.config/nvim/.cache/init.vim/.dein/rplugin/python3/chadtree/__init__.py", line 89, in run
    state = await self._curr_state()
  File "/Users/mhartington/.config/nvim/.cache/init.vim/.dein/rplugin/python3/chadtree/__init__.py", line 81, in _curr_state
    self.state = await initial_state(self.nvim, settings=self.settings)
  File "/Users/mhartington/.config/nvim/.cache/init.vim/.dein/rplugin/python3/chadtree/state.py", line 61, in initial
    vc = VCStatus() if settings.version_ctl.defer else await status()
  File "/Users/mhartington/.config/nvim/.cache/init.vim/.dein/rplugin/python3/chadtree/git.py", line 70, in status
    r, stats = await gather(root(), stat())
  File "/Users/mhartington/.config/nvim/.cache/init.vim/.dein/rplugin/python3/chadtree/git.py", line 17, in root
    ret = await call("git", "rev-parse", "--show-toplevel")
  File "/Users/mhartington/.config/nvim/.cache/init.vim/.dein/rplugin/python3/chadtree/da.py", line 53, in call
    proc = await create_subprocess_exec(prog, *args, stdout=PIPE, stderr=PIPE)
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/subprocess.py", line 217, in create_subp
rocess_exec
    stderr=stderr, **kwds)
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1544, in subproces
s_exec
    bufsize, **kwargs)
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subp
rocess_transport
    self._child_watcher_callback, transp)
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 941, in add_child_
handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
Cannot add child handler, the child watcher does not have a loop attached
```

Check my `checkhealth` results and python3 is all setup correctly. Not sure where to go from here.

**Comment by ms-jpq** [comment]
god dammit, I tested this on python `3.8` thinking it should just work for `3.7`, they changed something in `asyncio` between the two versions.

I think its this bug right here.

https://bugs.python.org/issue35621

**Comment by ms-jpq** [comment]
@mhartington 

Can you please try again after pulling my fix?

https://github.com/ms-jpq/chadtree/commit/81bb73ead206bc8a999c7632fd4c997d04adb444

**Comment by mhartington** [comment]
That seems to do it! Thanks for your work on this
