### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by manmadeharp** [ms-jpq/chadtree#200]
Error detected while processing function CHADon_stderr:                                                                                                                                                        
line    1:                                                                                                                                                                                                     
'type' object is not subscriptable                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                             
  File "/home/Finbar/.vim/bundle/chadtree/chadtree/transitions/version_ctl.py", line 40, in cont                                                                                                               
    vc = status(cwd)                                                                                                                                                                                           
  File "/home/Finbar/.vim/bundle/chadtree/chadtree/version_ctl/git.py", line 159, in status                                                                                                                    
    wait(cast(Sequence[Future[Any]], (r, s_main, s_sub)))                                                                                                                                                      
TypeError: 'type' object is not subscriptable    

Any hints as to how to fix this?
it constantly appears even when I try to close it.
Vim completely breaks when using it.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/201

sorry, I screwed up.

`Future[...]` only works on python `3.8.5` and up I think. and you are on a lower one, its ok, I fixed it though.

Please pull the latest changes <3

**Comment by manmadeharp** [comment]
Thank you!
