### ISSUE TITLE
Error detected while processing function CHADon_stderr

### ISSUE THREAD

**Issue by assawalhy** [ms-jpq/chadtree#228]
I opened a file that has a swap file not deleted then, after vim dialogue exited and I expected the file to open but I got this error message, the file opened at the end.

```
Error detected while processing function CHADon_stderr:
line    1:
Vim(edit):E325: ATTENTION
Traceback (most recent call last):
  File "/home/ms/.config/nvim/plugins/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/logging.py", l
ine 31, in with_suppress
    yield None
  File "/home/ms/.config/nvim/plugins/chadtree/chadtree/client.py", line 146, in wait
    threadsafe_call(nvim, cdraw)
  File "/home/ms/.config/nvim/plugins/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line
41, in threadsafe_call
    return cast(_T, fut.result())
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/ms/.config/nvim/plugins/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/lib.py", line
32, in cont
    ret = fn(*args, **kwargs)
  File "/home/ms/.config/nvim/plugins/chadtree/chadtree/client.py", line 124, in cdraw
    stage = handler(nvim, self._state, settings, *args)
  File "/home/ms/.config/nvim/plugins/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim_pp/rpc.py", line
54, in __call__
    return cast(_T, self._handler(nvim, *args, **kwargs))
  File "/home/ms/.config/nvim/plugins/chadtree/chadtree/transitions/click.py", line 70, in _primary
    return _click(
  File "/home/ms/.config/nvim/plugins/chadtree/chadtree/transitions/click.py", line 46, in _click
    nxt = open_file(
  File "/home/ms/.config/nvim/plugins/chadtree/chadtree/transitions/shared/open_file.py", line 109, in open_file
    _show_file(nvim, state=new_state, settings=settings, click_type=click_type)
  File "/home/ms/.config/nvim/plugins/chadtree/chadtree/transitions/shared/open_file.py", line 80, in _show_file
    nvim.command(f"edit! {escaped}")
  File "/home/ms/.config/nvim/plugins/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim/api/nvim.py", lin
e 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/home/ms/.config/nvim/plugins/chadtree/.vars/runtime/lib/python3.9/site-packages/pynvim/api/nvim.py", lin
e 182, in request

```

**Comment by ms-jpq** [comment]
https://stackoverflow.com/questions/45489008/vim-opening-file-e325-attention-error

probably cuz vim didnt shutdown correctly lasttime

**Comment by assawalhy** [comment]
> probably cuz vim didnt shutdown correctly lasttime

Is it ok to see this huge pile of red text?

![simplescreenrecorder-2021-09-05_06 43 35](https://user-images.githubusercontent.com/42011920/132116201-36db975e-3275-4668-9f9d-7aa5e5daa70c.gif)
