### ISSUE TITLE
Call to unknown function: getmarklist

### ISSUE THREAD

**Issue by daubaris** [ms-jpq/chadtree#256]
Hi, after updating `chadtree` version and upgrading its dependencies, it became impossible to use the plugin. The full error can be seen below.

```
Vim:E117: Unknown function: getmarklist
Traceback (most recent call last):
  File "/home/.vim/plugged/chadtree/chadtree/client.py", line 95, in wait
    go = threadsafe_call(nvim, cont)
  File "/home/.vim/plugged/chadtree/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line 74, in threadsafe_call
    return cast(_T, fut.result())
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/.vim/plugged/chadtree/.vars/runtime/lib/python3.8/site-packages/pynvim_pp/lib.py", line 65, in cont
    ret = fn(*args, **kwargs)
  File "/home/.vim/plugged/chadtree/chadtree/client.py", line 88, in cont
    self._state = initial_state(
  File "/home/.vim/plugged/chadtree/chadtree/state/load.py", line 42, in initial
    mks = markers(nvim)
  File "/home/.vim/plugged/chadtree/chadtree/nvim/markers.py", line 51, in markers
    bm = _bookmarks(nvim)
  File "/home/.vim/plugged/chadtree/chadtree/nvim/markers.py", line 19, in _bookmarks
    marks = nvim.funcs.getmarklist()
  File "/home/.vim/plugged/chadtree/.vars/runtime/lib/python3.8/site-packages/pynvim/api/nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/home/.vim/plugged/chadtree/.vars/runtime/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/.vim/plugged/chadtree/.vars/runtime/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:E117: Unknown function: getmarklist
```

**Comment by ms-jpq** [comment]
please pull again sorry, didnt know it was introduced in 0.5
