### ISSUE TITLE
Error detected while processing CHADon_exit on :CHADdeps

### ISSUE THREAD

**Issue by Zarainia** [ms-jpq/chadtree#265]
Not sure if there's anything specific I need to do, but running `:CHADdeps` just results in `Error detected while processing CHADon_exit: line 1: CHADTree EXITED - 1`

**Comment by sultanowskii** [comment]
Same here

**Comment by mad-briller** [comment]
This happened to me and was resolved by installing `python3-venv`

**Comment by Zarainia** [comment]
I did that and now it seems to be downloading and installing stuff, but at the end it still shows the same error. Looking at `:messages`, the culprit seems to be `distutils.command.bdist_wininst`, which is apparently removed in Python 3.10. 

```
Please update dependencies using :CHADdeps
-
-
Dependencies will be installed privately inside `chadtree/.vars`
`rm -rf chadtree/` will cleanly remove everything
Error detected while processing function CHADon_exit:
line    1:
CHADTree EXITED - 1
...
Collecting std2@ https://github.com/ms-jpq/std2/archive/a140163a756232a51067abb4fbd266094b83825c.tar.gz
  Using cached https://github.com/ms-jpq/std2/archive/a140163a756232a51067abb4fbd266094b83825c.tar.gz
Collecting pynvim_pp@ https://github.com/ms-jpq/pynvim_pp/archive/5f95e0c88cfdbb9762475b4866d7d3c47bb0629f.tar.gz
  Using cached https://github.com/ms-jpq/pynvim_pp/archive/5f95e0c88cfdbb9762475b4866d7d3c47bb0629f.tar.gz
Requirement already satisfied: setuptools in ./.vars/runtime/lib/python3.10/site-packages (from -r /home/zarainia/.vim/bundle/chadtree/requirements.txt (line 1)) (44.1.1)
Collecting setuptools
  Using cached setuptools-59.2.0-py3-none-any.whl (952 kB)
Collecting wheel
  Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Collecting pynvim==0.4.2
  Using cached pynvim-0.4.2.tar.gz (42 kB)
Collecting PyYAML==5.4.1
  Using cached PyYAML-5.4.1-cp310-cp310-linux_x86_64.whl
Collecting greenlet
  Using cached greenlet-1.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (155 kB)
Collecting msgpack>=0.5.0
  Using cached msgpack-1.0.2-cp310-cp310-linux_x86_64.whl
Using legacy 'setup.py install' for pynvim-pp, since package 'wheel' is not installed.
Using legacy 'setup.py install' for std2, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pynvim, since package 'wheel' is not installed.
Installing collected packages: msgpack, greenlet, pynvim, wheel, std2, setuptools, PyYAML, pynvim-pp
    Running setup.py install for pynvim: started
    Running setup.py install for pynvim: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/zarainia/.vim/bundle/chadtree/.vars/runtime/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e1j63lg9/pynvim_0
a4a227e58804b2d970e0ca6d61c2593/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e1j63lg9/pynvim_0a4a227e58804b2d970e0ca6d61c2593/setup.py'"'"';f=getattr(tokenize, '"'"'open
'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mkwec
mqx/install-record.txt --single-version-externally-managed --compile --install-headers /home/zarainia/.vim/bundle/chadtree/.vars/runtime/include/site/python3.10/pynvim
         cwd: /tmp/pip-install-e1j63lg9/pynvim_0a4a227e58804b2d970e0ca6d61c2593/
    Complete output (135 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/pynvim
    copying pynvim/util.py -> build/lib/pynvim
    copying pynvim/__init__.py -> build/lib/pynvim
    copying pynvim/compat.py -> build/lib/pynvim
    creating build/lib/pynvim/api
    copying pynvim/api/buffer.py -> build/lib/pynvim/api
    copying pynvim/api/tabpage.py -> build/lib/pynvim/api
    copying pynvim/api/nvim.py -> build/lib/pynvim/api
    copying pynvim/api/common.py -> build/lib/pynvim/api
    copying pynvim/api/window.py -> build/lib/pynvim/api
    copying pynvim/api/__init__.py -> build/lib/pynvim/api
    creating build/lib/pynvim/msgpack_rpc
    copying pynvim/msgpack_rpc/session.py -> build/lib/pynvim/msgpack_rpc
    copying pynvim/msgpack_rpc/async_session.py -> build/lib/pynvim/msgpack_rpc
    copying pynvim/msgpack_rpc/msgpack_stream.py -> build/lib/pynvim/msgpack_rpc
    copying pynvim/msgpack_rpc/__init__.py -> build/lib/pynvim/msgpack_rpc
    creating build/lib/pynvim/msgpack_rpc/event_loop
    copying pynvim/msgpack_rpc/event_loop/base.py -> build/lib/pynvim/msgpack_rpc/event_loop
    copying pynvim/msgpack_rpc/event_loop/uv.py -> build/lib/pynvim/msgpack_rpc/event_loop
    copying pynvim/msgpack_rpc/event_loop/__init__.py -> build/lib/pynvim/msgpack_rpc/event_loop
    copying pynvim/msgpack_rpc/event_loop/asyncio.py -> build/lib/pynvim/msgpack_rpc/event_loop
    creating build/lib/pynvim/plugin
    copying pynvim/plugin/script_host.py -> build/lib/pynvim/plugin
    copying pynvim/plugin/decorators.py -> build/lib/pynvim/plugin
    copying pynvim/plugin/host.py -> build/lib/pynvim/plugin
    copying pynvim/plugin/__init__.py -> build/lib/pynvim/plugin
    creating build/lib/neovim
    copying neovim/__init__.py -> build/lib/neovim
    creating build/lib/neovim/api
    copying neovim/api/__init__.py -> build/lib/neovim/api
    running install_lib
    creating /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim
    creating /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin
    copying build/lib/pynvim/plugin/script_host.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin
    copying build/lib/pynvim/plugin/decorators.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin
    copying build/lib/pynvim/plugin/host.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin
    copying build/lib/pynvim/plugin/__init__.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin
    creating /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc
    creating /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event_loop
    copying build/lib/pynvim/msgpack_rpc/event_loop/base.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event_loo
p
    copying build/lib/pynvim/msgpack_rpc/event_loop/uv.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event_loop
    copying build/lib/pynvim/msgpack_rpc/event_loop/__init__.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event
_loop
    copying build/lib/pynvim/msgpack_rpc/event_loop/asyncio.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event_
loop
    copying build/lib/pynvim/msgpack_rpc/session.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc
    copying build/lib/pynvim/msgpack_rpc/async_session.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc
    copying build/lib/pynvim/msgpack_rpc/msgpack_stream.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc
    copying build/lib/pynvim/msgpack_rpc/__init__.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc
    copying build/lib/pynvim/util.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim
    copying build/lib/pynvim/__init__.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim
    copying build/lib/pynvim/compat.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim
    creating /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api
    copying build/lib/pynvim/api/buffer.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api
    copying build/lib/pynvim/api/tabpage.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api
    copying build/lib/pynvim/api/nvim.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api
    copying build/lib/pynvim/api/common.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api
    copying build/lib/pynvim/api/window.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api
    copying build/lib/pynvim/api/__init__.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api
    creating /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/neovim
    copying build/lib/neovim/__init__.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/neovim
    creating /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/neovim/api
    copying build/lib/neovim/api/__init__.py -> /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/neovim/api
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin/script_host.py to script_host.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin/decorators.py to decorators.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin/host.py to host.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/plugin/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event_loop/base.py to base.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event_loop/uv.py to uv.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event_loop/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/event_loop/asyncio.py to asyncio.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/session.py to session.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/async_session.py to async_session.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/msgpack_stream.py to msgpack_stream.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/msgpack_rpc/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/util.py to util.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/compat.py to compat.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api/buffer.py to buffer.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api/tabpage.py to tabpage.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api/nvim.py to nvim.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api/common.py to common.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api/window.py to window.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim/api/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/neovim/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/neovim/api/__init__.py to __init__.cpython-310.pyc
    running install_egg_info
    running egg_info
    writing pynvim.egg-info/PKG-INFO
    writing dependency_links to pynvim.egg-info/dependency_links.txt
    writing requirements to pynvim.egg-info/requires.txt
    writing top-level names to pynvim.egg-info/top_level.txt
    reading manifest file 'pynvim.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pynvim.egg-info/SOURCES.txt'
    Copying pynvim.egg-info to /home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pynvim-0.4.2.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e1j63lg9/pynvim_0a4a227e58804b2d970e0ca6d61c2593/setup.py", line 37, in <module>
        setup(name='pynvim',
      File "/home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.10/distutils/command/install.py", line 634, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/setuptools/command/install_scripts.py", line 35, in run
        bw_cmd = self.get_finalized_command("bdist_wininst")
      File "/usr/lib/python3.10/distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python3.10/distutils/dist.py", line 857, in get_command_obj
        klass = self.get_command_class(command)
      File "/home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/setuptools/dist.py", line 834, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/zarainia/.vim/bundle/chadtree/.vars/runtime/lib/python3.10/site-packages/setuptools/command/bdist_wininst.py", line 1, in <module>
        import distutils.command.bdist_wininst as orig
    ModuleNotFoundError: No module named 'distutils.command.bdist_wininst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/zarainia/.vim/bundle/chadtree/.vars/runtime/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/
tmp/pip-install-e1j63lg9/pynvim_0a4a227e58804b2d970e0ca6d61c2593/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e1j63lg9/pynvim_0a4a227e58804b2d970e0ca6d61c2593/setup.py'"
'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' insta
ll --record /tmp/pip-record-mkwecmqx/install-record.txt --single-version-externally-managed --compile --install-headers /home/zarainia/.vim/bundle/chadtree/.vars/runtime/
include/site/python3.10/pynvim Check the logs for full command output.
Installation failed, check :message
Error detected while processing function CHADon_exit:
line    1:
CHADTree EXITED - 1
```
```

**Comment by duhduhdan** [comment]
I'm running into the same issue on macOS.

Whenever I `:PackerInstall` or, for sanity check `:PlugInstall`, and `chadtree` is finished downloading:
- I receive the normal message of `Please update dependencies using :CHADdeps`
- After confirming the message, I see the `Error detected while processing function CHADon_exit:` error
- Ignoring the error message and executing `:CHADdeps` results in the same error message.

I execute `:message` to see what went wrong, with the output of:

```
WARNING: Requirement 'std2@https://github.com/ms-jpq/std2/archive/48bb39b69ed631ef64eed6123443484133fd20fc.tar.gz' looks like a filename, but the file does not exist
WARNING: Requirement 'pynvim_pp@https://github.com/ms-jpq/pynvim_pp/archive/2cdf96bdb9b6cc17fa182bbd5ccfb3324daa0f1b.tar.gz' looks like a filename, but the file does not exist
Processing ./std2@https:/github.com/ms-jpq/std2/archive/48bb39b69ed631ef64eed6123443484133fd20fc.tar.gz
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '$HOME/.local/share/nvim/site/pack/packer/start/chadtree/std2@https:/github.com/ms-jpq/std2/archive/48bb39b69ed631ef64eed6123443484133fd
20fc.tar.gz'
WARNING: You are using pip version 19.2.3, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
- The `No such file or directory` path points to `'$HOME/.local/share/nvim/plugged/chadtree/std2@https:/github.com/ms-jpq/std2/archive/48bb39b69ed631ef64eed6123443484133f
d20fc.tar.gz'` when using `vim-plug`
- Running `pip --version` outputs `pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`

Thanks a ton for this sweet package! Works great on my older machine, but I'm trying to setup my new one.

**Comment by SsNiPeR1** [comment]
> This happened to me and was resolved by installing `python3-venv`

woo, thank you!
