### ISSUE TITLE
CHADdeps failing seemingly due to missing zlib

### ISSUE THREAD

**Issue by aryzing** [ms-jpq/chadtree#272]
EDIT: see [third post](https://github.com/ms-jpq/chadtree/issues/272#issuecomment-1000117553)

---

On my system, Ubuntu 21.04, I have both `python` (v2.7) and `python3` (v3.9) executables. Running `CHADdeps` produces the error,

```
Please install python3-venv separately. (apt, yum, apk, etc)
```

Package `python3-venv` is already installed, so I was puzzled by the error. To debug the issue, I created a small python program,

```python
# test.py
print("hello world")

from venv import EnvBuilder

print("foo")
```

When running it `python3 test.py`, all is good. However, `python test.py` throws an error with the the `venv` import,

```
Traceback (most recent call last):
  File "index.py", line 4, in <module>
    from venv import EnvBuilder
ImportError: No module named venv
```

I'm just getting started with Lua so I couldn't follow along the logic chadtree uses to load python3, but there's something about my system's config that, seemingly, is causing the [`chadtree.lua`](https://github.com/ms-jpq/chadtree/blob/3670a72f4e7a3a68434812134b61af3bcae86aaa/lua/chadtree.lua#L62) script to opt for `python` (v2.7).

Perhaps of use,

```vim
:lua print(pcall(vim.api.nvim_get_var, "python3_host_prog")) --> false Key not found: python3_host_prog
```

Is there something on my side I'm doing wrong or is there a bug here?

**Comment by aryzing** [comment]
I did a little digging. Modified the install script to print the error message,

```diff
-    except (ImportError, CalledProcessError):
+    except (ImportError, CalledProcessError) as e:
        msg = "Please install python3-venv separately. (apt, yum, apk, etc)"
        io_out.seek(0)
        print(msg, io_out.read(), file=stderr)
+       print(repr(e), io_out.read(), file=stderr)
        exit(1)
```

and this is what was printed,

```
CalledProcessError(1, ['/home/aryzing/.local/share/nvim/plugged/chadtree/.vars/runtime/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip'])
```

Does this help debug the issue?

**Comment by aryzing** [comment]
Further digging revealed a missing python dep, `zlib`,

```
~$ .local/share/nvim/plugged/chadtree/.vars/runtime/bin/python -Im ensurepip --upgrade --default-pip
Traceback (most recent call last):
  File "<frozen zipimport>", line 570, in _get_decompress_func
ModuleNotFoundError: No module named 'zlib'
```

My system already has the latest zlib deb,

```
zlib1g is already the newest version (1:1.2.11.dfsg-2ubuntu6).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu6).
```

but for some reason this isn't enough for `CHADdeps` to succeed. Any ideas?

**Comment by aryzing** [comment]
Finally solved it. 

1.  Install all deps as per [pyenv rec's](https://github.com/pyenv/pyenv/wiki#suggested-build-environment)
2.  [Download python from official site](https://www.python.org/downloads/) 
3.  From the downloaded files (Python 3.10.1), follow the instructions in `README.rst`. Notably, run 
    1. `./configure`
    2. `make`
    3. `make test`
    4. `make install`

Back in Neovim, `:CHADdeps` now runs successfully.
