### ISSUE TITLE
Invalid window id when using FZF/vimspector/etc

### ISSUE THREAD

**Issue by Frederick888** [ms-jpq/chadtree#63]
This happens from time to time when I use fzf.vim / [coc-fzf](https://github.com/antoinemadec/coc-fzf) / [vimspector](https://github.com/puremourning/vimspector). No idea why, perhaps because when the future gets resolved the window is already gone?

```
--  CHADTree
level:    ERROR
time:     2020-08-18 12:24:27
module:   __init__
line:     93
function: run
message:  |-
Invalid window id
Traceback (most recent call last):
  File "/Users/frederick/.vim/plugged/chadtree/rplugin/python3/chadtree/__init__.py", line 91, in run
    fut.result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/frederick/.vim/plugged/chadtree/rplugin/python3/chadtree/__init__.py", line 115, in run
    await redraw(self.nvim, state=self.state, focus=stage.focus)
  File "/Users/frederick/.vim/plugged/chadtree/rplugin/python3/chadtree/transitions.py", line 122, in redraw
    await call(nvim, cont)
  File "/Users/frederick/.vim/plugged/chadtree/rplugin/python3/chadtree/nvim.py", line 28, in cont
    ret = fn()
  File "/Users/frederick/.vim/plugged/chadtree/rplugin/python3/chadtree/transitions.py", line 120, in cont
    update_buffers(nvim, state=state, focus=focus)
  File "/Users/frederick/.vim/plugged/chadtree/rplugin/python3/chadtree/wm.py", line 273, in update_buffers
    for window, buffer in find_fm_windows(nvim):
  File "/Users/frederick/.vim/plugged/chadtree/rplugin/python3/chadtree/wm.py", line 49, in find_fm_windows
    buffer: Buffer = nvim.api.win_get_buf(window)
  File "/Users/frederick/Library/Python/3.8/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/frederick/Library/Python/3.8/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
```

**Comment by GaetanLepage** [comment]
I have the exact same error

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/101
will mostly fix
