### ISSUE TITLE
Give a short comprehensive error message when attemting to open a file in an unwritten buffer.

### ISSUE THREAD

**Issue by daknuett** [ms-jpq/chadtree#76]
**Steps to Reproduce**:

1. Open a file in a window.
2. Make changes in the buffer.
3. Go to CHADTree.
4. Select a different file and hit `<enter>` to open the file.

**Expected Behaviour**

CHADTree gives a message such as `E37: No write since last change`

**Actual Behaviour**

The error message

```
pynvim.api.common.NvimError: Failed to set buffer 1                                                                                                                                                                            
--  CHADTree
level:    ERROR
time:     2020-09-17 19:06:15
module:   __init__
line:     93
function: run
message:  |-
Failed to set buffer 7
Traceback (most recent call last):
  File "/home/daniel/.vim/plugged/chadtree/rplugin/python3/chadtree/__init__.py", line 91, in run
    fut.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/daniel/.vim/plugged/chadtree/rplugin/python3/chadtree/__init__.py", line 111, in run
    self.nvim, state=state, settings=self.settings, *args, **kwargs
  File "/home/daniel/.vim/plugged/chadtree/rplugin/python3/chadtree/transitions.py", line 279, in c_click
    await call(nvim, cont)
  File "/home/daniel/.vim/plugged/chadtree/rplugin/python3/chadtree/nvim.py", line 28, in cont
    ret = fn()
  File "/home/daniel/.vim/plugged/chadtree/rplugin/python3/chadtree/transitions.py", line 276, in cont
    click_type=click_type,
  File "/home/daniel/.vim/plugged/chadtree/rplugin/python3/chadtree/wm.py", line 215, in show_file
    nvim.api.win_set_buf(window, buffer)
  File "/home/daniel/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/daniel/.local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)

```

is displayed.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/chadtree/pull/103

**Comment by ms-jpq** [comment]
fixed now chadtree will open a new window if it cannot find one that is unwritten
